In [2]:
# import the libraries :
import os,sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings 
warnings.filterwarnings('ignore')
from scipy import stats

In [3]:
data=pd.read_csv("Bank-data_PCA.csv",index_col="Index")

In [4]:
data.head()

interest_rate  credit  Gender  previous  duration Churn
Index                                                         
0              1.334       0       1         0       117    no
1              0.767       0       0         1       274   yes
2              4.858       0       1         0       167    no
3              4.120       0       0         0       686   yes
4              4.856       0       1         0       159    no

In [5]:
data.isnull().sum()

interest_rate    0
credit           0
Gender           0
previous         0
duration         0
Churn            0
dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 518 entries, 0 to 517
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   interest_rate  518 non-null    float64
 1   credit         518 non-null    int64  
 2   Gender         518 non-null    int64  
 3   previous       518 non-null    int64  
 4   duration       518 non-null    int64  
 5   Churn          518 non-null    object 
dtypes: float64(1), int64(4), object(1)
memory usage: 28.3+ KB


In [7]:
data['Churn'].value_counts()

Churn
no     259
yes    259
Name: count, dtype: int64

In [8]:
#label encoding= other techniques to lebel encoding 
data['Churn']=data['Churn'].astype('category')
data['Churn']=data['Churn'].cat.codes

In [9]:
data['Churn'].value_counts()  # according tolabel alphabetical order no (N) comes first then yes(Y)

Churn
0    259
1    259
Name: count, dtype: int64

In [10]:
# inddependent = churn
# depen = 

In [11]:
df=data.copy()

In [12]:
x=data.drop(['Churn'],axis=1)  #  independenty

In [13]:
x.head()

interest_rate  credit  Gender  previous  duration
Index                                                   
0              1.334       0       1         0       117
1              0.767       0       0         1       274
2              4.858       0       1         0       167
3              4.120       0       0         0       686
4              4.856       0       1         0       159

In [14]:
y=data['Churn']

In [15]:
y.head()

Index
0    0
1    1
2    0
3    1
4    0
Name: Churn, dtype: int8

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=101)

In [18]:
#model buliding 
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [19]:
y_pred=lr.predict(x_test)

In [20]:
#training score
lr.score(x_train,y_train)

0.8502415458937198

In [21]:
#testing score
lr.score(x_test,y_test)

0.8557692307692307

In [22]:
y_pred=lr.predict(x_test)
y_pred

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int8)

In [23]:
from sklearn.metrics import accuracy_score
## training sccuracy
accuracy_score(y_train,lr.predict(x_train))

0.8502415458937198

In [24]:
accuracy_score(y_test,lr.predict(x_test))

0.8557692307692307

In [25]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [26]:
# confusion matrix
confusion_matrix(y_test,y_pred)

array([[51,  8],
       [ 7, 38]], dtype=int64)

In [27]:
# using PCA


In [28]:
from sklearn.decomposition import PCA
pca=PCA()

In [29]:
print(x_train.shape,x_test.shape)

(414, 5) (104, 5)


In [30]:
x_train_pca=pca.fit_transform(x_train)
x_test_pca=pca.fit_transform(x_test)

In [31]:
print(x_train.shape,x_test.shape)

(414, 5) (104, 5)


In [32]:
print(x_test_pca)

[[-1.85280606e+02  1.65150728e+00 -2.37912739e-01 -3.41373728e-02
  -3.69854437e-03]
 [-2.48280571e+02  1.58550632e+00 -2.41009011e-01 -4.01668354e-02
  -5.81947261e-03]
 [ 7.98722550e+02 -9.36300889e-01 -3.04014994e-01 -1.43650994e-01
   1.71591203e-02]
 [ 3.08720038e+02  1.27123122e+00 -2.42032729e-01 -3.73944662e-02
   9.88819064e-03]
 [-6.32763519e+01 -2.44573023e+00 -3.65560005e-01 -2.60280593e-01
  -1.39164702e-02]
 [-1.39276288e+02 -2.54689276e+00 -3.69976599e-01 -2.68766803e-01
  -1.65480899e-02]
 [ 2.47723313e+02 -1.96112060e+00 -3.45252351e-01 -2.21577840e-01
  -2.90809201e-03]
 [ 3.97230512e+01 -1.81019570e+00 -3.43808351e-01 -2.20723793e-01
  -8.65998595e-03]
 [ 7.27228934e+01 -1.77248890e+00  5.55758859e-01  8.55022779e-01
  -2.34509392e-01]
 [ 1.94722972e+02 -1.65471858e+00 -3.36408990e-01 -2.06278138e-01
  -3.46524481e-03]
 [-2.18280594e+02  1.62297036e+00 -2.39343702e-01 -3.69559641e-02
  -4.78904493e-03]
 [-1.42763160e+01 -2.53196194e+00 -4.64311832e-01  7.01530198e-01

In [33]:
explained_var=pca.explained_variance_ratio_

In [34]:
print(explained_var)

[9.99952575e-01 4.35619289e-05 2.71594389e-06 9.63707309e-07
 1.83348391e-07]


In [35]:
### pc1=0.9995
###PC2=0.000356
### PC3=0.000000715

In [36]:
pca_new=PCA(n_components=1)
x_train_pca=pca.fit_transform(x_train)
x_test_pca=pca.transform(x_test)

In [37]:
print(x_train_pca.shape,x_test_pca.shape)

(414, 5) (104, 5)


In [38]:
lr=LogisticRegression()
lr.fit(x_train_pca,y_train)

LogisticRegression()

In [39]:
#training score
y_pred_train=lr.predict(x_train_pca)
print('Training accuracy',accuracy_score(y_train,y_pred_train))


Training accuracy 0.8502415458937198


In [40]:
#testing score
y_pred_test=lr.predict(x_test_pca)
print('Training accuracy',accuracy_score(y_test,y_pred_test))


Training accuracy 0.8557692307692307


In [41]:
# confusion matrix
confusion_matrix(y_test,y_pred_test)

array([[51,  8],
       [ 7, 38]], dtype=int64)